// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package like.cn.dfs.model.client;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.PreCalculateResponse}
 */
public final class PreCalculateResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.PreCalculateResponse)
        PreCalculateResponseOrBuilder {
  public static final int FILECOUNT_FIELD_NUMBER = 1;
  public static final int TOTALSIZE_FIELD_NUMBER = 2;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.PreCalculateResponse)
  private static final like.cn.dfs.model.client.PreCalculateResponse DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<PreCalculateResponse>
          PARSER = new com.google.protobuf.AbstractParser<PreCalculateResponse>() {
    public PreCalculateResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new PreCalculateResponse(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.client.PreCalculateResponse();
  }

  private int fileCount_;
  private long totalSize_;
  private byte memoizedIsInitialized = -1;

  // Use PreCalculateResponse.newBuilder() to construct.
  private PreCalculateResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private PreCalculateResponse() {
    fileCount_ = 0;
    totalSize_ = 0L;
  }

  private PreCalculateResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            fileCount_ = input.readInt32();
            break;
          }
          case 16: {

            totalSize_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.client.PreCalculateResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.client.PreCalculateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<PreCalculateResponse> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_PreCalculateResponse_descriptor;
  }

  /**
   * <code>int32 fileCount = 1;</code>
   */
  public int getFileCount() {
    return fileCount_;
  }

  /**
   * <code>int64 totalSize = 2;</code>
   */
  public long getTotalSize() {
    return totalSize_;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.client.PreCalculateResponse)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.client.PreCalculateResponse other = ( like.cn.dfs.model.client.PreCalculateResponse ) obj;

    boolean result = true;
    result = result && (getFileCount()
            == other.getFileCount());
    result = result && (getTotalSize()
            == other.getTotalSize());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFileCount();
    hash = (37 * hash) + TOTALSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTotalSize());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PreCalculateResponse> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_PreCalculateResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.client.PreCalculateResponse.class, like.cn.dfs.model.client.PreCalculateResponse.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (fileCount_ != 0) {
      output.writeInt32(1, fileCount_);
    }
    if (totalSize_ != 0L) {
      output.writeInt64(2, totalSize_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fileCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, fileCount_);
    }
    if (totalSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(2, totalSize_);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.client.PreCalculateResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.PreCalculateResponse}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.PreCalculateResponse)
          like.cn.dfs.model.client.PreCalculateResponseOrBuilder {
    private int fileCount_;
    private long totalSize_;

    // Construct using like.cn.dfs.model.client.PreCalculateResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_PreCalculateResponse_descriptor;
    }

    public like.cn.dfs.model.client.PreCalculateResponse getDefaultInstanceForType() {
      return like.cn.dfs.model.client.PreCalculateResponse.getDefaultInstance();
    }

    public like.cn.dfs.model.client.PreCalculateResponse build() {
      like.cn.dfs.model.client.PreCalculateResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.client.PreCalculateResponse buildPartial() {
      like.cn.dfs.model.client.PreCalculateResponse result = new like.cn.dfs.model.client.PreCalculateResponse(this);
      result.fileCount_ = fileCount_;
      result.totalSize_ = totalSize_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      fileCount_ = 0;

      totalSize_ = 0L;

      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_PreCalculateResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.client.PreCalculateResponse.class, like.cn.dfs.model.client.PreCalculateResponse.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_PreCalculateResponse_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.client.PreCalculateResponse) {
        return mergeFrom(( like.cn.dfs.model.client.PreCalculateResponse ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.client.PreCalculateResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.client.PreCalculateResponse ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.client.PreCalculateResponse other) {
      if (other == like.cn.dfs.model.client.PreCalculateResponse.getDefaultInstance()) return this;
      if (other.getFileCount() != 0) {
        setFileCount(other.getFileCount());
      }
      if (other.getTotalSize() != 0L) {
        setTotalSize(other.getTotalSize());
      }
      onChanged();
      return this;
    }

    /**
     * <code>int32 fileCount = 1;</code>
     */
    public int getFileCount() {
      return fileCount_;
    }

    /**
     * <code>int32 fileCount = 1;</code>
     */
    public Builder setFileCount(int value) {

      fileCount_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 totalSize = 2;</code>
     */
    public long getTotalSize() {
      return totalSize_;
    }

    /**
     * <code>int64 totalSize = 2;</code>
     */
    public Builder setTotalSize(long value) {

      totalSize_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 fileCount = 1;</code>
     */
    public Builder clearFileCount() {

      fileCount_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>int64 totalSize = 2;</code>
     */
    public Builder clearTotalSize() {

      totalSize_ = 0L;
      onChanged();
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.PreCalculateResponse)
  }

}
