// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package like.cn.dfs.model.client;

public interface PreCalculateRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.PreCalculateRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string path = 1;</code>
     */
    java.lang.String getPath();

    /**
     * <code>string path = 1;</code>
     */
    com.google.protobuf.ByteString
    getPathBytes();
}
