// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs-client.proto

package like.cn.dfs.model.client;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.ReadStorageInfoResponse}
 */
public final class ReadStorageInfoResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.ReadStorageInfoResponse)
        ReadStorageInfoResponseOrBuilder {
  public static final int REPLICA_FIELD_NUMBER = 1;
  public static final int DATANODES_FIELD_NUMBER = 2;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.ReadStorageInfoResponse)
  private static final like.cn.dfs.model.client.ReadStorageInfoResponse DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<ReadStorageInfoResponse>
          PARSER = new com.google.protobuf.AbstractParser<ReadStorageInfoResponse>() {
    public ReadStorageInfoResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReadStorageInfoResponse(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.client.ReadStorageInfoResponse();
  }

  private int replica_;
  private volatile java.lang.Object datanodes_;
  private byte memoizedIsInitialized = -1;

  // Use ReadStorageInfoResponse.newBuilder() to construct.
  private ReadStorageInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ReadStorageInfoResponse() {
    replica_ = 0;
    datanodes_ = "";
  }

  private ReadStorageInfoResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            replica_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            datanodes_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.client.ReadStorageInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.client.ReadStorageInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ReadStorageInfoResponse> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_ReadStorageInfoResponse_descriptor;
  }

  /**
   * <code>int32 replica = 1;</code>
   */
  public int getReplica() {
    return replica_;
  }

  /**
   * <code>string datanodes = 2;</code>
   */
  public java.lang.String getDatanodes() {
    java.lang.Object ref = datanodes_;
    if (ref instanceof java.lang.String) {
      return ( java.lang.String ) ref;
    } else {
      com.google.protobuf.ByteString bs =
              ( com.google.protobuf.ByteString ) ref;
      java.lang.String s = bs.toStringUtf8();
      datanodes_ = s;
      return s;
    }
  }

  /**
   * <code>string datanodes = 2;</code>
   */
  public com.google.protobuf.ByteString
  getDatanodesBytes() {
    java.lang.Object ref = datanodes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      ( java.lang.String ) ref);
      datanodes_ = b;
      return b;
    } else {
      return ( com.google.protobuf.ByteString ) ref;
    }
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.client.ReadStorageInfoResponse)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.client.ReadStorageInfoResponse other = ( like.cn.dfs.model.client.ReadStorageInfoResponse ) obj;

    boolean result = true;
    result = result && (getReplica()
            == other.getReplica());
    result = result && getDatanodes()
            .equals(other.getDatanodes());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPLICA_FIELD_NUMBER;
    hash = (53 * hash) + getReplica();
    hash = (37 * hash) + DATANODES_FIELD_NUMBER;
    hash = (53 * hash) + getDatanodes().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReadStorageInfoResponse> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_ReadStorageInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.client.ReadStorageInfoResponse.class, like.cn.dfs.model.client.ReadStorageInfoResponse.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (replica_ != 0) {
      output.writeInt32(1, replica_);
    }
    if (!getDatanodesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datanodes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (replica_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, replica_);
    }
    if (!getDatanodesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datanodes_);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.client.ReadStorageInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.ReadStorageInfoResponse}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.ReadStorageInfoResponse)
          like.cn.dfs.model.client.ReadStorageInfoResponseOrBuilder {
    private int replica_;
    private java.lang.Object datanodes_ = "";

    // Construct using like.cn.dfs.model.client.ReadStorageInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_ReadStorageInfoResponse_descriptor;
    }

    public like.cn.dfs.model.client.ReadStorageInfoResponse getDefaultInstanceForType() {
      return like.cn.dfs.model.client.ReadStorageInfoResponse.getDefaultInstance();
    }

    public like.cn.dfs.model.client.ReadStorageInfoResponse build() {
      like.cn.dfs.model.client.ReadStorageInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.client.ReadStorageInfoResponse buildPartial() {
      like.cn.dfs.model.client.ReadStorageInfoResponse result = new like.cn.dfs.model.client.ReadStorageInfoResponse(this);
      result.replica_ = replica_;
      result.datanodes_ = datanodes_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      replica_ = 0;

      datanodes_ = "";

      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_ReadStorageInfoResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.client.ReadStorageInfoResponse.class, like.cn.dfs.model.client.ReadStorageInfoResponse.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.client.DfsClient.internal_static_com_ruyuan_dfs_common_proto_ReadStorageInfoResponse_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.client.ReadStorageInfoResponse) {
        return mergeFrom(( like.cn.dfs.model.client.ReadStorageInfoResponse ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.client.ReadStorageInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.client.ReadStorageInfoResponse ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.client.ReadStorageInfoResponse other) {
      if (other == like.cn.dfs.model.client.ReadStorageInfoResponse.getDefaultInstance()) return this;
      if (other.getReplica() != 0) {
        setReplica(other.getReplica());
      }
      if (!other.getDatanodes().isEmpty()) {
        datanodes_ = other.datanodes_;
        onChanged();
      }
      onChanged();
      return this;
    }

    /**
     * <code>int32 replica = 1;</code>
     */
    public int getReplica() {
      return replica_;
    }

    /**
     * <code>int32 replica = 1;</code>
     */
    public Builder setReplica(int value) {

      replica_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string datanodes = 2;</code>
     */
    public java.lang.String getDatanodes() {
      java.lang.Object ref = datanodes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                ( com.google.protobuf.ByteString ) ref;
        java.lang.String s = bs.toStringUtf8();
        datanodes_ = s;
        return s;
      } else {
        return ( java.lang.String ) ref;
      }
    }

    /**
     * <code>string datanodes = 2;</code>
     */
    public com.google.protobuf.ByteString
    getDatanodesBytes() {
      java.lang.Object ref = datanodes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        ( java.lang.String ) ref);
        datanodes_ = b;
        return b;
      } else {
        return ( com.google.protobuf.ByteString ) ref;
      }
    }

    /**
     * <code>string datanodes = 2;</code>
     */
    public Builder setDatanodesBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      datanodes_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string datanodes = 2;</code>
     */
    public Builder setDatanodes(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      datanodes_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 replica = 1;</code>
     */
    public Builder clearReplica() {

      replica_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string datanodes = 2;</code>
     */
    public Builder clearDatanodes() {

      datanodes_ = getDefaultInstance().getDatanodes();
      onChanged();
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.ReadStorageInfoResponse)
  }

}
