// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.AddReplicaNumRequest}
 */
public final class AddReplicaNumRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.AddReplicaNumRequest)
        AddReplicaNumRequestOrBuilder {
    public static final int FILENAME_FIELD_NUMBER = 1;
    public static final int REPLICANUM_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.AddReplicaNumRequest)
    private static final like.cn.dfs.model.namenode.AddReplicaNumRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<AddReplicaNumRequest>
            PARSER = new com.google.protobuf.AbstractParser<AddReplicaNumRequest>() {
        public AddReplicaNumRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AddReplicaNumRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.AddReplicaNumRequest();
    }

    private volatile java.lang.Object filename_;
    private int replicaNum_;
    private byte memoizedIsInitialized = -1;

    // Use AddReplicaNumRequest.newBuilder() to construct.
    private AddReplicaNumRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AddReplicaNumRequest() {
        filename_ = "";
        replicaNum_ = 0;
    }

    private AddReplicaNumRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!input.skipField(tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        filename_ = s;
                        break;
                    }
                    case 16: {

                        replicaNum_ = input.readInt32();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(like.cn.dfs.model.namenode.AddReplicaNumRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static like.cn.dfs.model.namenode.AddReplicaNumRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<AddReplicaNumRequest> parser() {
        return PARSER;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor;
    }

    /**
     * <code>string filename = 1;</code>
     */
    public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
            return ( java.lang.String ) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    ( com.google.protobuf.ByteString ) ref;
            java.lang.String s = bs.toStringUtf8();
            filename_ = s;
            return s;
        }
    }

    /**
     * <code>string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
    getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            ( java.lang.String ) ref);
            filename_ = b;
            return b;
        } else {
            return ( com.google.protobuf.ByteString ) ref;
        }
    }

    /**
     * <code>int32 replicaNum = 2;</code>
     */
    public int getReplicaNum() {
        return replicaNum_;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof like.cn.dfs.model.namenode.AddReplicaNumRequest)) {
            return super.equals(obj);
        }
        like.cn.dfs.model.namenode.AddReplicaNumRequest other = ( like.cn.dfs.model.namenode.AddReplicaNumRequest ) obj;

        boolean result = true;
        result = result && getFilename()
                .equals(other.getFilename());
        result = result && (getReplicaNum()
                == other.getReplicaNum());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
        hash = (37 * hash) + REPLICANUM_FIELD_NUMBER;
        hash = (53 * hash) + getReplicaNum();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public Builder newBuilderForType() {return newBuilder();}

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddReplicaNumRequest> getParserForType() {
        return PARSER;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        like.cn.dfs.model.namenode.AddReplicaNumRequest.class, like.cn.dfs.model.namenode.AddReplicaNumRequest.Builder.class);
    }

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getFilenameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
        }
        if (replicaNum_ != 0) {
            output.writeInt32(2, replicaNum_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getFilenameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
        }
        if (replicaNum_ != 0) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(2, replicaNum_);
        }
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    public like.cn.dfs.model.namenode.AddReplicaNumRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code com.ruyuan.dfs.common.proto.AddReplicaNumRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.AddReplicaNumRequest)
            like.cn.dfs.model.namenode.AddReplicaNumRequestOrBuilder {
        private java.lang.Object filename_ = "";
        private int replicaNum_;

        // Construct using like.cn.dfs.model.namenode.AddReplicaNumRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor;
        }

        public like.cn.dfs.model.namenode.AddReplicaNumRequest getDefaultInstanceForType() {
            return like.cn.dfs.model.namenode.AddReplicaNumRequest.getDefaultInstance();
        }

        public like.cn.dfs.model.namenode.AddReplicaNumRequest build() {
            like.cn.dfs.model.namenode.AddReplicaNumRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public like.cn.dfs.model.namenode.AddReplicaNumRequest buildPartial() {
            like.cn.dfs.model.namenode.AddReplicaNumRequest result = new like.cn.dfs.model.namenode.AddReplicaNumRequest(this);
            result.filename_ = filename_;
            result.replicaNum_ = replicaNum_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder clear() {
            super.clear();
            filename_ = "";

            replicaNum_ = 0;

            return this;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            like.cn.dfs.model.namenode.AddReplicaNumRequest.class, like.cn.dfs.model.namenode.AddReplicaNumRequest.Builder.class);
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_AddReplicaNumRequest_descriptor;
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof like.cn.dfs.model.namenode.AddReplicaNumRequest) {
                return mergeFrom(( like.cn.dfs.model.namenode.AddReplicaNumRequest ) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            like.cn.dfs.model.namenode.AddReplicaNumRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = ( like.cn.dfs.model.namenode.AddReplicaNumRequest ) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        public Builder mergeFrom(like.cn.dfs.model.namenode.AddReplicaNumRequest other) {
            if (other == like.cn.dfs.model.namenode.AddReplicaNumRequest.getDefaultInstance()) return this;
            if (!other.getFilename().isEmpty()) {
                filename_ = other.filename_;
                onChanged();
            }
            if (other.getReplicaNum() != 0) {
                setReplicaNum(other.getReplicaNum());
            }
            onChanged();
            return this;
        }

        /**
         * <code>string filename = 1;</code>
         */
        public java.lang.String getFilename() {
            java.lang.Object ref = filename_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        ( com.google.protobuf.ByteString ) ref;
                java.lang.String s = bs.toStringUtf8();
                filename_ = s;
                return s;
            } else {
                return ( java.lang.String ) ref;
            }
        }

        /**
         * <code>string filename = 1;</code>
         */
        public com.google.protobuf.ByteString
        getFilenameBytes() {
            java.lang.Object ref = filename_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                ( java.lang.String ) ref);
                filename_ = b;
                return b;
            } else {
                return ( com.google.protobuf.ByteString ) ref;
            }
        }

        /**
         * <code>string filename = 1;</code>
         */
        public Builder setFilenameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            filename_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int32 replicaNum = 2;</code>
         */
        public int getReplicaNum() {
            return replicaNum_;
        }

        /**
         * <code>int32 replicaNum = 2;</code>
         */
        public Builder setReplicaNum(int value) {

            replicaNum_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string filename = 1;</code>
         */
        public Builder setFilename(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            filename_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string filename = 1;</code>
         */
        public Builder clearFilename() {

            filename_ = getDefaultInstance().getFilename();
            onChanged();
            return this;
        }

        /**
         * <code>int32 replicaNum = 2;</code>
         */
        public Builder clearReplicaNum() {

            replicaNum_ = 0;
            onChanged();
            return this;
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }


        // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.AddReplicaNumRequest)
    }

}
