// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.ClientNameNodeInfo}
 */
public final class ClientNameNodeInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.ClientNameNodeInfo)
        ClientNameNodeInfoOrBuilder {
  public static final int CONFIG_FIELD_NUMBER = 1;
  public static final int SLOTS_FIELD_NUMBER = 2;
  public static final int BACKUP_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.ClientNameNodeInfo)
  private static final like.cn.dfs.model.namenode.ClientNameNodeInfo DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<ClientNameNodeInfo>
          PARSER = new com.google.protobuf.AbstractParser<ClientNameNodeInfo>() {
    public ClientNameNodeInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientNameNodeInfo(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.ClientNameNodeInfo();
  }

  private int bitField0_;
  private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> config_;
  private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> slots_;
  private volatile java.lang.Object backup_;
  private byte memoizedIsInitialized = -1;

  // Use ClientNameNodeInfo.newBuilder() to construct.
  private ClientNameNodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ClientNameNodeInfo() {
    backup_ = "";
  }

  private ClientNameNodeInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              config_ = com.google.protobuf.MapField.newMapField(
                      ConfigDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                    config__ = input.readMessage(
                    ConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            config_.getMutableMap().put(
                    config__.getKey(), config__.getValue());
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              slots_ = com.google.protobuf.MapField.newMapField(
                      SlotsDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
                    slots__ = input.readMessage(
                    SlotsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            slots_.getMutableMap().put(
                    slots__.getKey(), slots__.getValue());
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            backup_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.ClientNameNodeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.ClientNameNodeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ClientNameNodeInfo> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor;
  }

  public int getConfigCount() {
    return internalGetConfig().getMap().size();
  }

  /**
   * <code>map&lt;string, string&gt; config = 1;</code>
   */

  public boolean containsConfig(
          java.lang.String key) {
    if (key == null) {throw new java.lang.NullPointerException();}
    return internalGetConfig().getMap().containsKey(key);
  }

  /**
   * Use {@link #getConfigMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getConfig() {
    return getConfigMap();
  }

  /**
   * <code>map&lt;string, string&gt; config = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getConfigMap() {
    return internalGetConfig().getMap();
  }

  /**
   * <code>map&lt;string, string&gt; config = 1;</code>
   */

  public java.lang.String getConfigOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
    if (key == null) {throw new java.lang.NullPointerException();}
    java.util.Map<java.lang.String, java.lang.String> map =
            internalGetConfig().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /**
   * <code>map&lt;string, string&gt; config = 1;</code>
   */

  public java.lang.String getConfigOrThrow(
          java.lang.String key) {
    if (key == null) {throw new java.lang.NullPointerException();}
    java.util.Map<java.lang.String, java.lang.String> map =
            internalGetConfig().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public int getSlotsCount() {
    return internalGetSlots().getMap().size();
  }

  /**
   * <code>map&lt;int32, int32&gt; slots = 2;</code>
   */

  public boolean containsSlots(
          int key) {

    return internalGetSlots().getMap().containsKey(key);
  }

  /**
   * Use {@link #getSlotsMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getSlots() {
    return getSlotsMap();
  }

  /**
   * <code>map&lt;int32, int32&gt; slots = 2;</code>
   */

  public java.util.Map<java.lang.Integer, java.lang.Integer> getSlotsMap() {
    return internalGetSlots().getMap();
  }

  /**
   * <code>map&lt;int32, int32&gt; slots = 2;</code>
   */

  public int getSlotsOrDefault(
          int key,
          int defaultValue) {

    java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetSlots().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /**
   * <code>map&lt;int32, int32&gt; slots = 2;</code>
   */

  public int getSlotsOrThrow(
          int key) {

    java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetSlots().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  /**
   * <code>string backup = 3;</code>
   */
  public java.lang.String getBackup() {
    java.lang.Object ref = backup_;
    if (ref instanceof java.lang.String) {
      return ( java.lang.String ) ref;
    } else {
      com.google.protobuf.ByteString bs =
              ( com.google.protobuf.ByteString ) ref;
      java.lang.String s = bs.toStringUtf8();
      backup_ = s;
      return s;
    }
  }

  /**
   * <code>string backup = 3;</code>
   */
  public com.google.protobuf.ByteString
  getBackupBytes() {
    java.lang.Object ref = backup_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      ( java.lang.String ) ref);
      backup_ = b;
      return b;
    } else {
      return ( com.google.protobuf.ByteString ) ref;
    }
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.ClientNameNodeInfo)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.ClientNameNodeInfo other = ( like.cn.dfs.model.namenode.ClientNameNodeInfo ) obj;

    boolean result = true;
    result = result && internalGetConfig().equals(
            other.internalGetConfig());
    result = result && internalGetSlots().equals(
            other.internalGetSlots());
    result = result && getBackup()
            .equals(other.getBackup());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetConfig().getMap().isEmpty()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + internalGetConfig().hashCode();
    }
    if (!internalGetSlots().getMap().isEmpty()) {
      hash = (37 * hash) + SLOTS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetSlots().hashCode();
    }
    hash = (37 * hash) + BACKUP_FIELD_NUMBER;
    hash = (53 * hash) + getBackup().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientNameNodeInfo> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.ClientNameNodeInfo.class, like.cn.dfs.model.namenode.ClientNameNodeInfo.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
            .serializeStringMapTo(
                    output,
                    internalGetConfig(),
                    ConfigDefaultEntryHolder.defaultEntry,
                    1);
    com.google.protobuf.GeneratedMessageV3
            .serializeIntegerMapTo(
                    output,
                    internalGetSlots(),
                    SlotsDefaultEntryHolder.defaultEntry,
                    2);
    if (!getBackupBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, backup_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
            : internalGetConfig().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              config__ = ConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, config__);
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
            : internalGetSlots().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              slots__ = SlotsDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, slots__);
    }
    if (!getBackupBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, backup_);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
          int number) {
    switch (number) {
      case 1:
        return internalGetConfig();
      case 2:
        return internalGetSlots();
      default:
        throw new RuntimeException(
                "Invalid map field number: " + number);
    }
  }

  public like.cn.dfs.model.namenode.ClientNameNodeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetConfig() {
    if (config_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
              ConfigDefaultEntryHolder.defaultEntry);
    }
    return config_;
  }

  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetSlots() {
    if (slots_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
              SlotsDefaultEntryHolder.defaultEntry);
    }
    return slots_;
  }

  private static final class ConfigDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
            java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
                    .newDefaultInstance(
                            like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_ConfigEntry_descriptor,
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "",
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "");
  }

  private static final class SlotsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
            java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
                    .newDefaultInstance(
                            like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_SlotsEntry_descriptor,
                            com.google.protobuf.WireFormat.FieldType.INT32,
                            0,
                            com.google.protobuf.WireFormat.FieldType.INT32,
                            0);
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.ClientNameNodeInfo}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.ClientNameNodeInfo)
          like.cn.dfs.model.namenode.ClientNameNodeInfoOrBuilder {
    private int bitField0_;
    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> config_;
    private com.google.protobuf.MapField<
            java.lang.Integer, java.lang.Integer> slots_;
    private java.lang.Object backup_ = "";

    // Construct using like.cn.dfs.model.namenode.ClientNameNodeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor;
    }

    public like.cn.dfs.model.namenode.ClientNameNodeInfo getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.ClientNameNodeInfo.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.ClientNameNodeInfo build() {
      like.cn.dfs.model.namenode.ClientNameNodeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.ClientNameNodeInfo buildPartial() {
      like.cn.dfs.model.namenode.ClientNameNodeInfo result = new like.cn.dfs.model.namenode.ClientNameNodeInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.config_ = internalGetConfig();
      result.config_.makeImmutable();
      result.slots_ = internalGetSlots();
      result.slots_.makeImmutable();
      result.backup_ = backup_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      internalGetMutableConfig().clear();
      internalGetMutableSlots().clear();
      backup_ = "";

      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.ClientNameNodeInfo.class, like.cn.dfs.model.namenode.ClientNameNodeInfo.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientNameNodeInfo_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
      switch (number) {
        case 1:
          return internalGetConfig();
        case 2:
          return internalGetSlots();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
      switch (number) {
        case 1:
          return internalGetMutableConfig();
        case 2:
          return internalGetMutableSlots();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.ClientNameNodeInfo) {
        return mergeFrom(( like.cn.dfs.model.namenode.ClientNameNodeInfo ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.ClientNameNodeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.ClientNameNodeInfo ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.ClientNameNodeInfo other) {
      if (other == like.cn.dfs.model.namenode.ClientNameNodeInfo.getDefaultInstance()) return this;
      internalGetMutableConfig().mergeFrom(
              other.internalGetConfig());
      internalGetMutableSlots().mergeFrom(
              other.internalGetSlots());
      if (!other.getBackup().isEmpty()) {
        backup_ = other.backup_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public int getConfigCount() {
      return internalGetConfig().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public boolean containsConfig(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      return internalGetConfig().getMap().containsKey(key);
    }

    /**
     * Use {@link #getConfigMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getConfig() {
      return getConfigMap();
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getConfigMap() {
      return internalGetConfig().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public java.lang.String getConfigOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
      if (key == null) {throw new java.lang.NullPointerException();}
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetConfig().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public java.lang.String getConfigOrThrow(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetConfig().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public int getSlotsCount() {
      return internalGetSlots().getMap().size();
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public boolean containsSlots(
            int key) {

      return internalGetSlots().getMap().containsKey(key);
    }

    /**
     * Use {@link #getSlotsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getSlots() {
      return getSlotsMap();
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getSlotsMap() {
      return internalGetSlots().getMap();
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public int getSlotsOrDefault(
            int key,
            int defaultValue) {

      java.util.Map<java.lang.Integer, java.lang.Integer> map =
              internalGetSlots().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public int getSlotsOrThrow(
            int key) {

      java.util.Map<java.lang.Integer, java.lang.Integer> map =
              internalGetSlots().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    /**
     * <code>string backup = 3;</code>
     */
    public java.lang.String getBackup() {
      java.lang.Object ref = backup_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                ( com.google.protobuf.ByteString ) ref;
        java.lang.String s = bs.toStringUtf8();
        backup_ = s;
        return s;
      } else {
        return ( java.lang.String ) ref;
      }
    }

    /**
     * <code>string backup = 3;</code>
     */
    public com.google.protobuf.ByteString
    getBackupBytes() {
      java.lang.Object ref = backup_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        ( java.lang.String ) ref);
        backup_ = b;
        return b;
      } else {
        return ( com.google.protobuf.ByteString ) ref;
      }
    }

    /**
     * <code>string backup = 3;</code>
     */
    public Builder setBackupBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      backup_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string backup = 3;</code>
     */
    public Builder setBackup(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      backup_ = value;
      onChanged();
      return this;
    }

    public Builder clearConfig() {
      internalGetMutableConfig().getMutableMap()
              .clear();
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public Builder removeConfig(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      internalGetMutableConfig().getMutableMap()
              .remove(key);
      return this;
    }

    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableConfig() {
      return internalGetMutableConfig().getMutableMap();
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */
    public Builder putConfig(
            java.lang.String key,
            java.lang.String value) {
      if (key == null) {throw new java.lang.NullPointerException();}
      if (value == null) {throw new java.lang.NullPointerException();}
      internalGetMutableConfig().getMutableMap()
              .put(key, value);
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; config = 1;</code>
     */

    public Builder putAllConfig(
            java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableConfig().getMutableMap()
              .putAll(values);
      return this;
    }

    public Builder clearSlots() {
      internalGetMutableSlots().getMutableMap()
              .clear();
      return this;
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public Builder removeSlots(
            int key) {

      internalGetMutableSlots().getMutableMap()
              .remove(key);
      return this;
    }

    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableSlots() {
      return internalGetMutableSlots().getMutableMap();
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */
    public Builder putSlots(
            int key,
            int value) {


      internalGetMutableSlots().getMutableMap()
              .put(key, value);
      return this;
    }

    /**
     * <code>map&lt;int32, int32&gt; slots = 2;</code>
     */

    public Builder putAllSlots(
            java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableSlots().getMutableMap()
              .putAll(values);
      return this;
    }

    /**
     * <code>string backup = 3;</code>
     */
    public Builder clearBackup() {

      backup_ = getDefaultInstance().getBackup();
      onChanged();
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetConfig() {
      if (config_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                ConfigDefaultEntryHolder.defaultEntry);
      }
      return config_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableConfig() {
      onChanged();
      if (config_ == null) {
        config_ = com.google.protobuf.MapField.newMapField(
                ConfigDefaultEntryHolder.defaultEntry);
      }
      if (!config_.isMutable()) {
        config_ = config_.copy();
      }
      return config_;
    }

    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetSlots() {
      if (slots_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                SlotsDefaultEntryHolder.defaultEntry);
      }
      return slots_;
    }

    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableSlots() {
      onChanged();
      if (slots_ == null) {
        slots_ = com.google.protobuf.MapField.newMapField(
                SlotsDefaultEntryHolder.defaultEntry);
      }
      if (!slots_.isMutable()) {
        slots_ = slots_.copy();
      }
      return slots_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.ClientNameNodeInfo)
  }

}
