// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.ClientDataNodeInfo}
 */
public final class ClientDataNodeInfo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.ClientDataNodeInfo)
        ClientDataNodeInfoOrBuilder {
  public static final int CLIENTDATANODES_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.ClientDataNodeInfo)
  private static final like.cn.dfs.model.namenode.ClientDataNodeInfo DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<ClientDataNodeInfo>
          PARSER = new com.google.protobuf.AbstractParser<ClientDataNodeInfo>() {
    public ClientDataNodeInfo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientDataNodeInfo(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.ClientDataNodeInfo();
  }

  private java.util.List<like.cn.dfs.model.namenode.ClientDataNode> clientDataNodes_;
  private byte memoizedIsInitialized = -1;

  // Use ClientDataNodeInfo.newBuilder() to construct.
  private ClientDataNodeInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private ClientDataNodeInfo() {
    clientDataNodes_ = java.util.Collections.emptyList();
  }

  private ClientDataNodeInfo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              clientDataNodes_ = new java.util.ArrayList<like.cn.dfs.model.namenode.ClientDataNode>();
              mutable_bitField0_ |= 0x00000001;
            }
            clientDataNodes_.add(
                    input.readMessage(like.cn.dfs.model.namenode.ClientDataNode.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        clientDataNodes_ = java.util.Collections.unmodifiableList(clientDataNodes_);
      }
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.ClientDataNodeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.ClientDataNodeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<ClientDataNodeInfo> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  public java.util.List<like.cn.dfs.model.namenode.ClientDataNode> getClientDataNodesList() {
    return clientDataNodes_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  public like.cn.dfs.model.namenode.ClientDataNode getClientDataNodes(int index) {
    return clientDataNodes_.get(index);
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  public int getClientDataNodesCount() {
    return clientDataNodes_.size();
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  public java.util.List<? extends like.cn.dfs.model.namenode.ClientDataNodeOrBuilder>
  getClientDataNodesOrBuilderList() {
    return clientDataNodes_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
   */
  public like.cn.dfs.model.namenode.ClientDataNodeOrBuilder getClientDataNodesOrBuilder(
          int index) {
    return clientDataNodes_.get(index);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.ClientDataNodeInfo)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.ClientDataNodeInfo other = ( like.cn.dfs.model.namenode.ClientDataNodeInfo ) obj;

    boolean result = true;
    result = result && getClientDataNodesList()
            .equals(other.getClientDataNodesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getClientDataNodesCount() > 0) {
      hash = (37 * hash) + CLIENTDATANODES_FIELD_NUMBER;
      hash = (53 * hash) + getClientDataNodesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientDataNodeInfo> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.ClientDataNodeInfo.class, like.cn.dfs.model.namenode.ClientDataNodeInfo.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < clientDataNodes_.size(); i++) {
      output.writeMessage(1, clientDataNodes_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < clientDataNodes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, clientDataNodes_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.namenode.ClientDataNodeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.ClientDataNodeInfo}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.ClientDataNodeInfo)
          like.cn.dfs.model.namenode.ClientDataNodeInfoOrBuilder {
    private int bitField0_;
    private java.util.List<like.cn.dfs.model.namenode.ClientDataNode> clientDataNodes_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.ClientDataNode, like.cn.dfs.model.namenode.ClientDataNode.Builder, like.cn.dfs.model.namenode.ClientDataNodeOrBuilder> clientDataNodesBuilder_;

    // Construct using like.cn.dfs.model.namenode.ClientDataNodeInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor;
    }

    public like.cn.dfs.model.namenode.ClientDataNodeInfo getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.ClientDataNodeInfo.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.ClientDataNodeInfo build() {
      like.cn.dfs.model.namenode.ClientDataNodeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.ClientDataNodeInfo buildPartial() {
      like.cn.dfs.model.namenode.ClientDataNodeInfo result = new like.cn.dfs.model.namenode.ClientDataNodeInfo(this);
      int from_bitField0_ = bitField0_;
      if (clientDataNodesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          clientDataNodes_ = java.util.Collections.unmodifiableList(clientDataNodes_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.clientDataNodes_ = clientDataNodes_;
      } else {
        result.clientDataNodes_ = clientDataNodesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      if (clientDataNodesBuilder_ == null) {
        clientDataNodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        clientDataNodesBuilder_.clear();
      }
      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.ClientDataNodeInfo.class, like.cn.dfs.model.namenode.ClientDataNodeInfo.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_ClientDataNodeInfo_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.ClientDataNodeInfo) {
        return mergeFrom(( like.cn.dfs.model.namenode.ClientDataNodeInfo ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.ClientDataNodeInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.ClientDataNodeInfo ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.ClientDataNodeInfo other) {
      if (other == like.cn.dfs.model.namenode.ClientDataNodeInfo.getDefaultInstance()) return this;
      if (clientDataNodesBuilder_ == null) {
        if (!other.clientDataNodes_.isEmpty()) {
          if (clientDataNodes_.isEmpty()) {
            clientDataNodes_ = other.clientDataNodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClientDataNodesIsMutable();
            clientDataNodes_.addAll(other.clientDataNodes_);
          }
          onChanged();
        }
      } else {
        if (!other.clientDataNodes_.isEmpty()) {
          if (clientDataNodesBuilder_.isEmpty()) {
            clientDataNodesBuilder_.dispose();
            clientDataNodesBuilder_ = null;
            clientDataNodes_ = other.clientDataNodes_;
            bitField0_ = (bitField0_ & ~0x00000001);
            clientDataNodesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getClientDataNodesFieldBuilder() : null;
          } else {
            clientDataNodesBuilder_.addAllMessages(other.clientDataNodes_);
          }
        }
      }
      onChanged();
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.ClientDataNode> getClientDataNodesList() {
      if (clientDataNodesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(clientDataNodes_);
      } else {
        return clientDataNodesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public like.cn.dfs.model.namenode.ClientDataNode getClientDataNodes(int index) {
      if (clientDataNodesBuilder_ == null) {
        return clientDataNodes_.get(index);
      } else {
        return clientDataNodesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public int getClientDataNodesCount() {
      if (clientDataNodesBuilder_ == null) {
        return clientDataNodes_.size();
      } else {
        return clientDataNodesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public java.util.List<? extends like.cn.dfs.model.namenode.ClientDataNodeOrBuilder>
    getClientDataNodesOrBuilderList() {
      if (clientDataNodesBuilder_ != null) {
        return clientDataNodesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(clientDataNodes_);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public like.cn.dfs.model.namenode.ClientDataNodeOrBuilder getClientDataNodesOrBuilder(
            int index) {
      if (clientDataNodesBuilder_ == null) {
        return clientDataNodes_.get(index);
      } else {
        return clientDataNodesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder setClientDataNodes(
            int index, like.cn.dfs.model.namenode.ClientDataNode value) {
      if (clientDataNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientDataNodesIsMutable();
        clientDataNodes_.set(index, value);
        onChanged();
      } else {
        clientDataNodesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder setClientDataNodes(
            int index, like.cn.dfs.model.namenode.ClientDataNode.Builder builderForValue) {
      if (clientDataNodesBuilder_ == null) {
        ensureClientDataNodesIsMutable();
        clientDataNodes_.set(index, builderForValue.build());
        onChanged();
      } else {
        clientDataNodesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder addClientDataNodes(like.cn.dfs.model.namenode.ClientDataNode value) {
      if (clientDataNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientDataNodesIsMutable();
        clientDataNodes_.add(value);
        onChanged();
      } else {
        clientDataNodesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder addClientDataNodes(
            int index, like.cn.dfs.model.namenode.ClientDataNode value) {
      if (clientDataNodesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientDataNodesIsMutable();
        clientDataNodes_.add(index, value);
        onChanged();
      } else {
        clientDataNodesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder addClientDataNodes(
            like.cn.dfs.model.namenode.ClientDataNode.Builder builderForValue) {
      if (clientDataNodesBuilder_ == null) {
        ensureClientDataNodesIsMutable();
        clientDataNodes_.add(builderForValue.build());
        onChanged();
      } else {
        clientDataNodesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder addClientDataNodes(
            int index, like.cn.dfs.model.namenode.ClientDataNode.Builder builderForValue) {
      if (clientDataNodesBuilder_ == null) {
        ensureClientDataNodesIsMutable();
        clientDataNodes_.add(index, builderForValue.build());
        onChanged();
      } else {
        clientDataNodesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder addAllClientDataNodes(
            java.lang.Iterable<? extends like.cn.dfs.model.namenode.ClientDataNode> values) {
      if (clientDataNodesBuilder_ == null) {
        ensureClientDataNodesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, clientDataNodes_);
        onChanged();
      } else {
        clientDataNodesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder clearClientDataNodes() {
      if (clientDataNodesBuilder_ == null) {
        clientDataNodes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        clientDataNodesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public Builder removeClientDataNodes(int index) {
      if (clientDataNodesBuilder_ == null) {
        ensureClientDataNodesIsMutable();
        clientDataNodes_.remove(index);
        onChanged();
      } else {
        clientDataNodesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public like.cn.dfs.model.namenode.ClientDataNode.Builder getClientDataNodesBuilder(
            int index) {
      return getClientDataNodesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public like.cn.dfs.model.namenode.ClientDataNode.Builder addClientDataNodesBuilder() {
      return getClientDataNodesFieldBuilder().addBuilder(
              like.cn.dfs.model.namenode.ClientDataNode.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public like.cn.dfs.model.namenode.ClientDataNode.Builder addClientDataNodesBuilder(
            int index) {
      return getClientDataNodesFieldBuilder().addBuilder(
              index, like.cn.dfs.model.namenode.ClientDataNode.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.ClientDataNode clientDataNodes = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.ClientDataNode.Builder>
    getClientDataNodesBuilderList() {
      return getClientDataNodesFieldBuilder().getBuilderList();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getClientDataNodesFieldBuilder();
      }
    }

    private void ensureClientDataNodesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        clientDataNodes_ = new java.util.ArrayList<like.cn.dfs.model.namenode.ClientDataNode>(clientDataNodes_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.ClientDataNode, like.cn.dfs.model.namenode.ClientDataNode.Builder, like.cn.dfs.model.namenode.ClientDataNodeOrBuilder>
    getClientDataNodesFieldBuilder() {
      if (clientDataNodesBuilder_ == null) {
        clientDataNodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                like.cn.dfs.model.namenode.ClientDataNode, like.cn.dfs.model.namenode.ClientDataNode.Builder, like.cn.dfs.model.namenode.ClientDataNodeOrBuilder>(
                clientDataNodes_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        clientDataNodes_ = null;
      }
      return clientDataNodesBuilder_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.ClientDataNodeInfo)
  }

}
