// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

public interface FetchDataNodeByFilenameResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.FetchDataNodeByFilenameResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    java.util.List<like.cn.dfs.model.common.DataNode>
    getDatanodesList();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    like.cn.dfs.model.common.DataNode getDatanodes(int index);

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    int getDatanodesCount();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    java.util.List<? extends like.cn.dfs.model.common.DataNodeOrBuilder>
    getDatanodesOrBuilderList();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.DataNode datanodes = 1;</code>
     */
    like.cn.dfs.model.common.DataNodeOrBuilder getDatanodesOrBuilder(
            int index);
}
