// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchMetaDataResponse}
 */
public final class FetchMetaDataResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
        FetchMetaDataResponseOrBuilder {
  public static final int FILES_FIELD_NUMBER = 1;
  public static final int COMPLETED_FIELD_NUMBER = 2;
  public static final int NODEID_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
  private static final like.cn.dfs.model.namenode.FetchMetaDataResponse DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<FetchMetaDataResponse>
          PARSER = new com.google.protobuf.AbstractParser<FetchMetaDataResponse>() {
    public FetchMetaDataResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchMetaDataResponse(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.FetchMetaDataResponse();
  }

  private int bitField0_;
  private java.util.List<like.cn.dfs.model.namenode.Metadata> files_;
  private boolean completed_;
  private int nodeId_;
  private byte memoizedIsInitialized = -1;

  // Use FetchMetaDataResponse.newBuilder() to construct.
  private FetchMetaDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private FetchMetaDataResponse() {
    files_ = java.util.Collections.emptyList();
    completed_ = false;
    nodeId_ = 0;
  }

  private FetchMetaDataResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              files_ = new java.util.ArrayList<like.cn.dfs.model.namenode.Metadata>();
              mutable_bitField0_ |= 0x00000001;
            }
            files_.add(
                    input.readMessage(like.cn.dfs.model.namenode.Metadata.parser(), extensionRegistry));
            break;
          }
          case 16: {

            completed_ = input.readBool();
            break;
          }
          case 24: {

            nodeId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        files_ = java.util.Collections.unmodifiableList(files_);
      }
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.FetchMetaDataResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.FetchMetaDataResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<FetchMetaDataResponse> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  public java.util.List<like.cn.dfs.model.namenode.Metadata> getFilesList() {
    return files_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  public like.cn.dfs.model.namenode.Metadata getFiles(int index) {
    return files_.get(index);
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  public int getFilesCount() {
    return files_.size();
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  public java.util.List<? extends like.cn.dfs.model.namenode.MetadataOrBuilder>
  getFilesOrBuilderList() {
    return files_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
   */
  public like.cn.dfs.model.namenode.MetadataOrBuilder getFilesOrBuilder(
          int index) {
    return files_.get(index);
  }

  /**
   * <code>bool completed = 2;</code>
   */
  public boolean getCompleted() {
    return completed_;
  }

  /**
   * <code>int32 nodeId = 3;</code>
   */
  public int getNodeId() {
    return nodeId_;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.FetchMetaDataResponse)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.FetchMetaDataResponse other = ( like.cn.dfs.model.namenode.FetchMetaDataResponse ) obj;

    boolean result = true;
    result = result && getFilesList()
            .equals(other.getFilesList());
    result = result && (getCompleted()
            == other.getCompleted());
    result = result && (getNodeId()
            == other.getNodeId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFilesCount() > 0) {
      hash = (37 * hash) + FILES_FIELD_NUMBER;
      hash = (53 * hash) + getFilesList().hashCode();
    }
    hash = (37 * hash) + COMPLETED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getCompleted());
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchMetaDataResponse> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.FetchMetaDataResponse.class, like.cn.dfs.model.namenode.FetchMetaDataResponse.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < files_.size(); i++) {
      output.writeMessage(1, files_.get(i));
    }
    if (completed_ != false) {
      output.writeBool(2, completed_);
    }
    if (nodeId_ != 0) {
      output.writeInt32(3, nodeId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < files_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, files_.get(i));
    }
    if (completed_ != false) {
      size += com.google.protobuf.CodedOutputStream
              .computeBoolSize(2, completed_);
    }
    if (nodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(3, nodeId_);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.namenode.FetchMetaDataResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.FetchMetaDataResponse}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
          like.cn.dfs.model.namenode.FetchMetaDataResponseOrBuilder {
    private int bitField0_;
    private java.util.List<like.cn.dfs.model.namenode.Metadata> files_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.Metadata, like.cn.dfs.model.namenode.Metadata.Builder, like.cn.dfs.model.namenode.MetadataOrBuilder> filesBuilder_;
    private boolean completed_;
    private int nodeId_;

    // Construct using like.cn.dfs.model.namenode.FetchMetaDataResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor;
    }

    public like.cn.dfs.model.namenode.FetchMetaDataResponse getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.FetchMetaDataResponse.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.FetchMetaDataResponse build() {
      like.cn.dfs.model.namenode.FetchMetaDataResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.FetchMetaDataResponse buildPartial() {
      like.cn.dfs.model.namenode.FetchMetaDataResponse result = new like.cn.dfs.model.namenode.FetchMetaDataResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (filesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          files_ = java.util.Collections.unmodifiableList(files_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.files_ = files_;
      } else {
        result.files_ = filesBuilder_.build();
      }
      result.completed_ = completed_;
      result.nodeId_ = nodeId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      if (filesBuilder_ == null) {
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        filesBuilder_.clear();
      }
      completed_ = false;

      nodeId_ = 0;

      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.FetchMetaDataResponse.class, like.cn.dfs.model.namenode.FetchMetaDataResponse.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_FetchMetaDataResponse_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.FetchMetaDataResponse) {
        return mergeFrom(( like.cn.dfs.model.namenode.FetchMetaDataResponse ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.FetchMetaDataResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.FetchMetaDataResponse ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.FetchMetaDataResponse other) {
      if (other == like.cn.dfs.model.namenode.FetchMetaDataResponse.getDefaultInstance()) return this;
      if (filesBuilder_ == null) {
        if (!other.files_.isEmpty()) {
          if (files_.isEmpty()) {
            files_ = other.files_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFilesIsMutable();
            files_.addAll(other.files_);
          }
          onChanged();
        }
      } else {
        if (!other.files_.isEmpty()) {
          if (filesBuilder_.isEmpty()) {
            filesBuilder_.dispose();
            filesBuilder_ = null;
            files_ = other.files_;
            bitField0_ = (bitField0_ & ~0x00000001);
            filesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getFilesFieldBuilder() : null;
          } else {
            filesBuilder_.addAllMessages(other.files_);
          }
        }
      }
      if (other.getCompleted() != false) {
        setCompleted(other.getCompleted());
      }
      if (other.getNodeId() != 0) {
        setNodeId(other.getNodeId());
      }
      onChanged();
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.Metadata> getFilesList() {
      if (filesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(files_);
      } else {
        return filesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public like.cn.dfs.model.namenode.Metadata getFiles(int index) {
      if (filesBuilder_ == null) {
        return files_.get(index);
      } else {
        return filesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public int getFilesCount() {
      if (filesBuilder_ == null) {
        return files_.size();
      } else {
        return filesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public java.util.List<? extends like.cn.dfs.model.namenode.MetadataOrBuilder>
    getFilesOrBuilderList() {
      if (filesBuilder_ != null) {
        return filesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(files_);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public like.cn.dfs.model.namenode.MetadataOrBuilder getFilesOrBuilder(
            int index) {
      if (filesBuilder_ == null) {
        return files_.get(index);
      } else {
        return filesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>bool completed = 2;</code>
     */
    public boolean getCompleted() {
      return completed_;
    }

    /**
     * <code>bool completed = 2;</code>
     */
    public Builder setCompleted(boolean value) {

      completed_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 nodeId = 3;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    /**
     * <code>int32 nodeId = 3;</code>
     */
    public Builder setNodeId(int value) {

      nodeId_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder setFiles(
            int index, like.cn.dfs.model.namenode.Metadata value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.set(index, value);
        onChanged();
      } else {
        filesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder setFiles(
            int index, like.cn.dfs.model.namenode.Metadata.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.set(index, builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder addFiles(like.cn.dfs.model.namenode.Metadata value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.add(value);
        onChanged();
      } else {
        filesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder addFiles(
            int index, like.cn.dfs.model.namenode.Metadata value) {
      if (filesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFilesIsMutable();
        files_.add(index, value);
        onChanged();
      } else {
        filesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder addFiles(
            like.cn.dfs.model.namenode.Metadata.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.add(builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder addFiles(
            int index, like.cn.dfs.model.namenode.Metadata.Builder builderForValue) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.add(index, builderForValue.build());
        onChanged();
      } else {
        filesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder addAllFiles(
            java.lang.Iterable<? extends like.cn.dfs.model.namenode.Metadata> values) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, files_);
        onChanged();
      } else {
        filesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder clearFiles() {
      if (filesBuilder_ == null) {
        files_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        filesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public Builder removeFiles(int index) {
      if (filesBuilder_ == null) {
        ensureFilesIsMutable();
        files_.remove(index);
        onChanged();
      } else {
        filesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public like.cn.dfs.model.namenode.Metadata.Builder getFilesBuilder(
            int index) {
      return getFilesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public like.cn.dfs.model.namenode.Metadata.Builder addFilesBuilder() {
      return getFilesFieldBuilder().addBuilder(
              like.cn.dfs.model.namenode.Metadata.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public like.cn.dfs.model.namenode.Metadata.Builder addFilesBuilder(
            int index) {
      return getFilesFieldBuilder().addBuilder(
              index, like.cn.dfs.model.namenode.Metadata.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.Metadata.Builder>
    getFilesBuilderList() {
      return getFilesFieldBuilder().getBuilderList();
    }

    /**
     * <code>bool completed = 2;</code>
     */
    public Builder clearCompleted() {

      completed_ = false;
      onChanged();
      return this;
    }

    /**
     * <code>int32 nodeId = 3;</code>
     */
    public Builder clearNodeId() {

      nodeId_ = 0;
      onChanged();
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFilesFieldBuilder();
      }
    }

    private void ensureFilesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        files_ = new java.util.ArrayList<like.cn.dfs.model.namenode.Metadata>(files_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.Metadata, like.cn.dfs.model.namenode.Metadata.Builder, like.cn.dfs.model.namenode.MetadataOrBuilder>
    getFilesFieldBuilder() {
      if (filesBuilder_ == null) {
        filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                like.cn.dfs.model.namenode.Metadata, like.cn.dfs.model.namenode.Metadata.Builder, like.cn.dfs.model.namenode.MetadataOrBuilder>(
                files_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        files_ = null;
      }
      return filesBuilder_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
  }

}
