// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

public interface FetchMetaDataResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.FetchMetaDataResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    java.util.List<like.cn.dfs.model.namenode.Metadata>
    getFilesList();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    like.cn.dfs.model.namenode.Metadata getFiles(int index);

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    int getFilesCount();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    java.util.List<? extends like.cn.dfs.model.namenode.MetadataOrBuilder>
    getFilesOrBuilderList();

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.Metadata files = 1;</code>
     */
    like.cn.dfs.model.namenode.MetadataOrBuilder getFilesOrBuilder(
            int index);

    /**
     * <code>bool completed = 2;</code>
     */
    boolean getCompleted();

    /**
     * <code>int32 nodeId = 3;</code>
     */
    int getNodeId();
}
