// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.Metadata}
 */
public final class Metadata extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.Metadata)
        MetadataOrBuilder {
  public static final int FILENAME_FIELD_NUMBER = 1;
  public static final int TYPE_FIELD_NUMBER = 2;
  public static final int HOSTNAME_FIELD_NUMBER = 3;
  public static final int FILESIZE_FIELD_NUMBER = 4;
  public static final int ATTR_FIELD_NUMBER = 5;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.Metadata)
  private static final like.cn.dfs.model.namenode.Metadata DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<Metadata>
          PARSER = new com.google.protobuf.AbstractParser<Metadata>() {
    public Metadata parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new Metadata(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.Metadata();
  }

  private int bitField0_;
  private volatile java.lang.Object fileName_;
  private int type_;
  private volatile java.lang.Object hostname_;
  private long fileSize_;
  private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attr_;
  private byte memoizedIsInitialized = -1;

  // Use Metadata.newBuilder() to construct.
  private Metadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Metadata() {
    fileName_ = "";
    type_ = 0;
    hostname_ = "";
    fileSize_ = 0L;
  }

  private Metadata(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fileName_ = s;
            break;
          }
          case 16: {

            type_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            hostname_ = s;
            break;
          }
          case 32: {

            fileSize_ = input.readInt64();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              attr_ = com.google.protobuf.MapField.newMapField(
                      AttrDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000010;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                    attr__ = input.readMessage(
                    AttrDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attr_.getMutableMap().put(
                    attr__.getKey(), attr__.getValue());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.Metadata parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.Metadata parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.Metadata parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.Metadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.Metadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<Metadata> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor;
  }

  /**
   * <code>string fileName = 1;</code>
   */
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return ( java.lang.String ) ref;
    } else {
      com.google.protobuf.ByteString bs =
              ( com.google.protobuf.ByteString ) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }

  /**
   * <code>string fileName = 1;</code>
   */
  public com.google.protobuf.ByteString
  getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      ( java.lang.String ) ref);
      fileName_ = b;
      return b;
    } else {
      return ( com.google.protobuf.ByteString ) ref;
    }
  }

  /**
   * <code>int32 type = 2;</code>
   */
  public int getType() {
    return type_;
  }

  /**
   * <code>string hostname = 3;</code>
   */
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return ( java.lang.String ) ref;
    } else {
      com.google.protobuf.ByteString bs =
              ( com.google.protobuf.ByteString ) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }

  /**
   * <code>string hostname = 3;</code>
   */
  public com.google.protobuf.ByteString
  getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      ( java.lang.String ) ref);
      hostname_ = b;
      return b;
    } else {
      return ( com.google.protobuf.ByteString ) ref;
    }
  }

  /**
   * <code>int64 fileSize = 4;</code>
   */
  public long getFileSize() {
    return fileSize_;
  }

  public int getAttrCount() {
    return internalGetAttr().getMap().size();
  }

  /**
   * <code>map&lt;string, string&gt; attr = 5;</code>
   */

  public boolean containsAttr(
          java.lang.String key) {
    if (key == null) {throw new java.lang.NullPointerException();}
    return internalGetAttr().getMap().containsKey(key);
  }

  /**
   * Use {@link #getAttrMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttr() {
    return getAttrMap();
  }

  /**
   * <code>map&lt;string, string&gt; attr = 5;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getAttrMap() {
    return internalGetAttr().getMap();
  }

  /**
   * <code>map&lt;string, string&gt; attr = 5;</code>
   */

  public java.lang.String getAttrOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
    if (key == null) {throw new java.lang.NullPointerException();}
    java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttr().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /**
   * <code>map&lt;string, string&gt; attr = 5;</code>
   */

  public java.lang.String getAttrOrThrow(
          java.lang.String key) {
    if (key == null) {throw new java.lang.NullPointerException();}
    java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttr().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.Metadata)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.Metadata other = ( like.cn.dfs.model.namenode.Metadata ) obj;

    boolean result = true;
    result = result && getFileName()
            .equals(other.getFileName());
    result = result && (getType()
            == other.getType());
    result = result && getHostname()
            .equals(other.getHostname());
    result = result && (getFileSize()
            == other.getFileSize());
    result = result && internalGetAttr().equals(
            other.internalGetAttr());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostname().hashCode();
    hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFileSize());
    if (!internalGetAttr().getMap().isEmpty()) {
      hash = (37 * hash) + ATTR_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttr().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Metadata> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.Metadata.class, like.cn.dfs.model.namenode.Metadata.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileName_);
    }
    if (type_ != 0) {
      output.writeInt32(2, type_);
    }
    if (!getHostnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hostname_);
    }
    if (fileSize_ != 0L) {
      output.writeInt64(4, fileSize_);
    }
    com.google.protobuf.GeneratedMessageV3
            .serializeStringMapTo(
                    output,
                    internalGetAttr(),
                    AttrDefaultEntryHolder.defaultEntry,
                    5);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileName_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, type_);
    }
    if (!getHostnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hostname_);
    }
    if (fileSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(4, fileSize_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
            : internalGetAttr().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attr__ = AttrDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(5, attr__);
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  @SuppressWarnings({"rawtypes"})
  protected com.google.protobuf.MapField internalGetMapField(
          int number) {
    switch (number) {
      case 5:
        return internalGetAttr();
      default:
        throw new RuntimeException(
                "Invalid map field number: " + number);
    }
  }

  public like.cn.dfs.model.namenode.Metadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttr() {
    if (attr_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
              AttrDefaultEntryHolder.defaultEntry);
    }
    return attr_;
  }

  private static final class AttrDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
            java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
                    .newDefaultInstance(
                            like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_AttrEntry_descriptor,
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "",
                            com.google.protobuf.WireFormat.FieldType.STRING,
                            "");
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.Metadata}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.Metadata)
          like.cn.dfs.model.namenode.MetadataOrBuilder {
    private int bitField0_;
    private java.lang.Object fileName_ = "";
    private int type_;
    private java.lang.Object hostname_ = "";
    private long fileSize_;
    private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> attr_;

    // Construct using like.cn.dfs.model.namenode.Metadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor;
    }

    public like.cn.dfs.model.namenode.Metadata getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.Metadata.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.Metadata build() {
      like.cn.dfs.model.namenode.Metadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.Metadata buildPartial() {
      like.cn.dfs.model.namenode.Metadata result = new like.cn.dfs.model.namenode.Metadata(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.fileName_ = fileName_;
      result.type_ = type_;
      result.hostname_ = hostname_;
      result.fileSize_ = fileSize_;
      result.attr_ = internalGetAttr();
      result.attr_.makeImmutable();
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      fileName_ = "";

      type_ = 0;

      hostname_ = "";

      fileSize_ = 0L;

      internalGetMutableAttr().clear();
      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.Metadata.class, like.cn.dfs.model.namenode.Metadata.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_Metadata_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
            int number) {
      switch (number) {
        case 5:
          return internalGetAttr();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
      switch (number) {
        case 5:
          return internalGetMutableAttr();
        default:
          throw new RuntimeException(
                  "Invalid map field number: " + number);
      }
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.Metadata) {
        return mergeFrom(( like.cn.dfs.model.namenode.Metadata ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.Metadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.Metadata ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.Metadata other) {
      if (other == like.cn.dfs.model.namenode.Metadata.getDefaultInstance()) return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.getHostname().isEmpty()) {
        hostname_ = other.hostname_;
        onChanged();
      }
      if (other.getFileSize() != 0L) {
        setFileSize(other.getFileSize());
      }
      internalGetMutableAttr().mergeFrom(
              other.internalGetAttr());
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 1;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                ( com.google.protobuf.ByteString ) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return ( java.lang.String ) ref;
      }
    }

    /**
     * <code>string fileName = 1;</code>
     */
    public com.google.protobuf.ByteString
    getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        ( java.lang.String ) ref);
        fileName_ = b;
        return b;
      } else {
        return ( com.google.protobuf.ByteString ) ref;
      }
    }

    /**
     * <code>string fileName = 1;</code>
     */
    public Builder setFileNameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      fileName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    /**
     * <code>int32 type = 2;</code>
     */
    public Builder setType(int value) {

      type_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string hostname = 3;</code>
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
                ( com.google.protobuf.ByteString ) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return ( java.lang.String ) ref;
      }
    }

    /**
     * <code>string hostname = 3;</code>
     */
    public com.google.protobuf.ByteString
    getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        ( java.lang.String ) ref);
        hostname_ = b;
        return b;
      } else {
        return ( com.google.protobuf.ByteString ) ref;
      }
    }

    /**
     * <code>string hostname = 3;</code>
     */
    public Builder setHostnameBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      hostname_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int64 fileSize = 4;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    /**
     * <code>int64 fileSize = 4;</code>
     */
    public Builder setFileSize(long value) {

      fileSize_ = value;
      onChanged();
      return this;
    }

    public int getAttrCount() {
      return internalGetAttr().getMap().size();
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public boolean containsAttr(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      return internalGetAttr().getMap().containsKey(key);
    }

    /**
     * Use {@link #getAttrMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttr() {
      return getAttrMap();
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttrMap() {
      return internalGetAttr().getMap();
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public java.lang.String getAttrOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
      if (key == null) {throw new java.lang.NullPointerException();}
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetAttr().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public java.lang.String getAttrOrThrow(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      java.util.Map<java.lang.String, java.lang.String> map =
              internalGetAttr().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    /**
     * <code>string hostname = 3;</code>
     */
    public Builder setHostname(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      hostname_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 1;</code>
     */
    public Builder setFileName(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      fileName_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string fileName = 1;</code>
     */
    public Builder clearFileName() {

      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }

    /**
     * <code>int32 type = 2;</code>
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string hostname = 3;</code>
     */
    public Builder clearHostname() {

      hostname_ = getDefaultInstance().getHostname();
      onChanged();
      return this;
    }

    /**
     * <code>int64 fileSize = 4;</code>
     */
    public Builder clearFileSize() {

      fileSize_ = 0L;
      onChanged();
      return this;
    }

    public Builder clearAttr() {
      internalGetMutableAttr().getMutableMap()
              .clear();
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public Builder removeAttr(
            java.lang.String key) {
      if (key == null) {throw new java.lang.NullPointerException();}
      internalGetMutableAttr().getMutableMap()
              .remove(key);
      return this;
    }

    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAttr() {
      return internalGetMutableAttr().getMutableMap();
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */
    public Builder putAttr(
            java.lang.String key,
            java.lang.String value) {
      if (key == null) {throw new java.lang.NullPointerException();}
      if (value == null) {throw new java.lang.NullPointerException();}
      internalGetMutableAttr().getMutableMap()
              .put(key, value);
      return this;
    }

    /**
     * <code>map&lt;string, string&gt; attr = 5;</code>
     */

    public Builder putAllAttr(
            java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttr().getMutableMap()
              .putAll(values);
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttr() {
      if (attr_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
                AttrDefaultEntryHolder.defaultEntry);
      }
      return attr_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAttr() {
      onChanged();
      if (attr_ == null) {
        attr_ = com.google.protobuf.MapField.newMapField(
                AttrDefaultEntryHolder.defaultEntry);
      }
      if (!attr_.isMutable()) {
        attr_ = attr_.copy();
      }
      return attr_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.Metadata)
  }

}
