// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

public interface TrashResumeResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.TrashResumeResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 fileCount = 1;</code>
     */
    int getFileCount();
}
