// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.UserStorageEntity}
 */
public final class UserStorageEntity extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.UserStorageEntity)
        UserStorageEntityOrBuilder {
  public static final int STORAGESIZE_FIELD_NUMBER = 1;
  public static final int FILECOUNT_FIELD_NUMBER = 2;
  public static final int DATANODES_FIELD_NUMBER = 3;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.UserStorageEntity)
  private static final like.cn.dfs.model.namenode.UserStorageEntity DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<UserStorageEntity>
          PARSER = new com.google.protobuf.AbstractParser<UserStorageEntity>() {
    public UserStorageEntity parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserStorageEntity(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.UserStorageEntity();
  }

  private int bitField0_;
  private long storageSize_;
  private int fileCount_;
  private com.google.protobuf.LazyStringList dataNodes_;
  private byte memoizedIsInitialized = -1;

  // Use UserStorageEntity.newBuilder() to construct.
  private UserStorageEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private UserStorageEntity() {
    storageSize_ = 0L;
    fileCount_ = 0;
    dataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  private UserStorageEntity(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            storageSize_ = input.readInt64();
            break;
          }
          case 16: {

            fileCount_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              dataNodes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            dataNodes_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        dataNodes_ = dataNodes_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.UserStorageEntity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.UserStorageEntity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<UserStorageEntity> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor;
  }

  /**
   * <code>int64 storageSize = 1;</code>
   */
  public long getStorageSize() {
    return storageSize_;
  }

  /**
   * <code>int32 fileCount = 2;</code>
   */
  public int getFileCount() {
    return fileCount_;
  }

  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
  getDataNodesList() {
    return dataNodes_;
  }

  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  public int getDataNodesCount() {
    return dataNodes_.size();
  }

  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  public java.lang.String getDataNodes(int index) {
    return dataNodes_.get(index);
  }

  /**
   * <code>repeated string dataNodes = 3;</code>
   */
  public com.google.protobuf.ByteString
  getDataNodesBytes(int index) {
    return dataNodes_.getByteString(index);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.UserStorageEntity)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.UserStorageEntity other = ( like.cn.dfs.model.namenode.UserStorageEntity ) obj;

    boolean result = true;
    result = result && (getStorageSize()
            == other.getStorageSize());
    result = result && (getFileCount()
            == other.getFileCount());
    result = result && getDataNodesList()
            .equals(other.getDataNodesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STORAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getStorageSize());
    hash = (37 * hash) + FILECOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getFileCount();
    if (getDataNodesCount() > 0) {
      hash = (37 * hash) + DATANODES_FIELD_NUMBER;
      hash = (53 * hash) + getDataNodesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserStorageEntity> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.UserStorageEntity.class, like.cn.dfs.model.namenode.UserStorageEntity.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (storageSize_ != 0L) {
      output.writeInt64(1, storageSize_);
    }
    if (fileCount_ != 0) {
      output.writeInt32(2, fileCount_);
    }
    for (int i = 0; i < dataNodes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataNodes_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (storageSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt64Size(1, storageSize_);
    }
    if (fileCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(2, fileCount_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < dataNodes_.size(); i++) {
        dataSize += computeStringSizeNoTag(dataNodes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDataNodesList().size();
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.namenode.UserStorageEntity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.UserStorageEntity}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.UserStorageEntity)
          like.cn.dfs.model.namenode.UserStorageEntityOrBuilder {
    private int bitField0_;
    private long storageSize_;
    private int fileCount_;
    private com.google.protobuf.LazyStringList dataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;

    // Construct using like.cn.dfs.model.namenode.UserStorageEntity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor;
    }

    public like.cn.dfs.model.namenode.UserStorageEntity getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.UserStorageEntity.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.UserStorageEntity build() {
      like.cn.dfs.model.namenode.UserStorageEntity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.UserStorageEntity buildPartial() {
      like.cn.dfs.model.namenode.UserStorageEntity result = new like.cn.dfs.model.namenode.UserStorageEntity(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.storageSize_ = storageSize_;
      result.fileCount_ = fileCount_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        dataNodes_ = dataNodes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.dataNodes_ = dataNodes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      storageSize_ = 0L;

      fileCount_ = 0;

      dataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.UserStorageEntity.class, like.cn.dfs.model.namenode.UserStorageEntity.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserStorageEntity_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.UserStorageEntity) {
        return mergeFrom(( like.cn.dfs.model.namenode.UserStorageEntity ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.UserStorageEntity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.UserStorageEntity ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.UserStorageEntity other) {
      if (other == like.cn.dfs.model.namenode.UserStorageEntity.getDefaultInstance()) return this;
      if (other.getStorageSize() != 0L) {
        setStorageSize(other.getStorageSize());
      }
      if (other.getFileCount() != 0) {
        setFileCount(other.getFileCount());
      }
      if (!other.dataNodes_.isEmpty()) {
        if (dataNodes_.isEmpty()) {
          dataNodes_ = other.dataNodes_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureDataNodesIsMutable();
          dataNodes_.addAll(other.dataNodes_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    /**
     * <code>int64 storageSize = 1;</code>
     */
    public long getStorageSize() {
      return storageSize_;
    }

    /**
     * <code>int64 storageSize = 1;</code>
     */
    public Builder setStorageSize(long value) {

      storageSize_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 fileCount = 2;</code>
     */
    public int getFileCount() {
      return fileCount_;
    }

    /**
     * <code>int32 fileCount = 2;</code>
     */
    public Builder setFileCount(int value) {

      fileCount_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
    getDataNodesList() {
      return dataNodes_.getUnmodifiableView();
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public int getDataNodesCount() {
      return dataNodes_.size();
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public java.lang.String getDataNodes(int index) {
      return dataNodes_.get(index);
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public com.google.protobuf.ByteString
    getDataNodesBytes(int index) {
      return dataNodes_.getByteString(index);
    }

    /**
     * <code>int64 storageSize = 1;</code>
     */
    public Builder clearStorageSize() {

      storageSize_ = 0L;
      onChanged();
      return this;
    }

    /**
     * <code>int32 fileCount = 2;</code>
     */
    public Builder clearFileCount() {

      fileCount_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public Builder setDataNodes(
            int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataNodesIsMutable();
      dataNodes_.set(index, value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public Builder addDataNodes(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataNodesIsMutable();
      dataNodes_.add(value);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public Builder addAllDataNodes(
            java.lang.Iterable<java.lang.String> values) {
      ensureDataNodesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataNodes_);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public Builder clearDataNodes() {
      dataNodes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    /**
     * <code>repeated string dataNodes = 3;</code>
     */
    public Builder addDataNodesBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureDataNodesIsMutable();
      dataNodes_.add(value);
      onChanged();
      return this;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    private void ensureDataNodesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        dataNodes_ = new com.google.protobuf.LazyStringArrayList(dataNodes_);
        bitField0_ |= 0x00000004;
      }
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.UserStorageEntity)
  }

}
