// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.UserChangeEvent}
 */
public final class UserChangeEvent extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.UserChangeEvent)
        UserChangeEventOrBuilder {
  public static final int EVENTTYPE_FIELD_NUMBER = 1;
  public static final int USERENTITY_FIELD_NUMBER = 2;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.UserChangeEvent)
  private static final like.cn.dfs.model.namenode.UserChangeEvent DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<UserChangeEvent>
          PARSER = new com.google.protobuf.AbstractParser<UserChangeEvent>() {
    public UserChangeEvent parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserChangeEvent(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.UserChangeEvent();
  }

  private int eventType_;
  private like.cn.dfs.model.namenode.UserEntity userEntity_;
  private byte memoizedIsInitialized = -1;

  // Use UserChangeEvent.newBuilder() to construct.
  private UserChangeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private UserChangeEvent() {
    eventType_ = 0;
  }

  private UserChangeEvent(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            eventType_ = input.readInt32();
            break;
          }
          case 18: {
            like.cn.dfs.model.namenode.UserEntity.Builder subBuilder = null;
            if (userEntity_ != null) {
              subBuilder = userEntity_.toBuilder();
            }
            userEntity_ = input.readMessage(like.cn.dfs.model.namenode.UserEntity.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userEntity_);
              userEntity_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.UserChangeEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.UserChangeEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<UserChangeEvent> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor;
  }

  /**
   * <code>int32 eventType = 1;</code>
   */
  public int getEventType() {
    return eventType_;
  }

  /**
   * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
   */
  public boolean hasUserEntity() {
    return userEntity_ != null;
  }

  /**
   * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
   */
  public like.cn.dfs.model.namenode.UserEntity getUserEntity() {
    return userEntity_ == null ? like.cn.dfs.model.namenode.UserEntity.getDefaultInstance() : userEntity_;
  }

  /**
   * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
   */
  public like.cn.dfs.model.namenode.UserEntityOrBuilder getUserEntityOrBuilder() {
    return getUserEntity();
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.UserChangeEvent)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.UserChangeEvent other = ( like.cn.dfs.model.namenode.UserChangeEvent ) obj;

    boolean result = true;
    result = result && (getEventType()
            == other.getEventType());
    result = result && (hasUserEntity() == other.hasUserEntity());
    if (hasUserEntity()) {
      result = result && getUserEntity()
              .equals(other.getUserEntity());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType();
    if (hasUserEntity()) {
      hash = (37 * hash) + USERENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getUserEntity().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserChangeEvent> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.UserChangeEvent.class, like.cn.dfs.model.namenode.UserChangeEvent.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (eventType_ != 0) {
      output.writeInt32(1, eventType_);
    }
    if (userEntity_ != null) {
      output.writeMessage(2, getUserEntity());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
              .computeInt32Size(1, eventType_);
    }
    if (userEntity_ != null) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(2, getUserEntity());
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.namenode.UserChangeEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.UserChangeEvent}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.UserChangeEvent)
          like.cn.dfs.model.namenode.UserChangeEventOrBuilder {
    private int eventType_;
    private like.cn.dfs.model.namenode.UserEntity userEntity_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
            like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder> userEntityBuilder_;

    // Construct using like.cn.dfs.model.namenode.UserChangeEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor;
    }

    public like.cn.dfs.model.namenode.UserChangeEvent getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.UserChangeEvent.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.UserChangeEvent build() {
      like.cn.dfs.model.namenode.UserChangeEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.UserChangeEvent buildPartial() {
      like.cn.dfs.model.namenode.UserChangeEvent result = new like.cn.dfs.model.namenode.UserChangeEvent(this);
      result.eventType_ = eventType_;
      if (userEntityBuilder_ == null) {
        result.userEntity_ = userEntity_;
      } else {
        result.userEntity_ = userEntityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      eventType_ = 0;

      if (userEntityBuilder_ == null) {
        userEntity_ = null;
      } else {
        userEntity_ = null;
        userEntityBuilder_ = null;
      }
      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.UserChangeEvent.class, like.cn.dfs.model.namenode.UserChangeEvent.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserChangeEvent_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.UserChangeEvent) {
        return mergeFrom(( like.cn.dfs.model.namenode.UserChangeEvent ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.UserChangeEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.UserChangeEvent ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.UserChangeEvent other) {
      if (other == like.cn.dfs.model.namenode.UserChangeEvent.getDefaultInstance()) return this;
      if (other.getEventType() != 0) {
        setEventType(other.getEventType());
      }
      if (other.hasUserEntity()) {
        mergeUserEntity(other.getUserEntity());
      }
      onChanged();
      return this;
    }

    /**
     * <code>int32 eventType = 1;</code>
     */
    public int getEventType() {
      return eventType_;
    }

    /**
     * <code>int32 eventType = 1;</code>
     */
    public Builder setEventType(int value) {

      eventType_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public boolean hasUserEntity() {
      return userEntityBuilder_ != null || userEntity_ != null;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity getUserEntity() {
      if (userEntityBuilder_ == null) {
        return userEntity_ == null ? like.cn.dfs.model.namenode.UserEntity.getDefaultInstance() : userEntity_;
      } else {
        return userEntityBuilder_.getMessage();
      }
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public Builder setUserEntity(like.cn.dfs.model.namenode.UserEntity value) {
      if (userEntityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userEntity_ = value;
        onChanged();
      } else {
        userEntityBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public Builder setUserEntity(
            like.cn.dfs.model.namenode.UserEntity.Builder builderForValue) {
      if (userEntityBuilder_ == null) {
        userEntity_ = builderForValue.build();
        onChanged();
      } else {
        userEntityBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public like.cn.dfs.model.namenode.UserEntityOrBuilder getUserEntityOrBuilder() {
      if (userEntityBuilder_ != null) {
        return userEntityBuilder_.getMessageOrBuilder();
      } else {
        return userEntity_ == null ?
                like.cn.dfs.model.namenode.UserEntity.getDefaultInstance() : userEntity_;
      }
    }

    /**
     * <code>int32 eventType = 1;</code>
     */
    public Builder clearEventType() {

      eventType_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public Builder mergeUserEntity(like.cn.dfs.model.namenode.UserEntity value) {
      if (userEntityBuilder_ == null) {
        if (userEntity_ != null) {
          userEntity_ =
                  like.cn.dfs.model.namenode.UserEntity.newBuilder(userEntity_)
                          .mergeFrom(value)
                          .buildPartial();
        } else {
          userEntity_ = value;
        }
        onChanged();
      } else {
        userEntityBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public Builder clearUserEntity() {
      if (userEntityBuilder_ == null) {
        userEntity_ = null;
        onChanged();
      } else {
        userEntity_ = null;
        userEntityBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity.Builder getUserEntityBuilder() {

      onChanged();
      return getUserEntityFieldBuilder().getBuilder();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }

    /**
     * <code>.com.ruyuan.dfs.common.proto.UserEntity userEntity = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder>
    getUserEntityFieldBuilder() {
      if (userEntityBuilder_ == null) {
        userEntityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder>(
                getUserEntity(),
                getParentForChildren(),
                isClean());
        userEntity_ = null;
      }
      return userEntityBuilder_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.UserChangeEvent)
  }

}
