// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: namenode.proto

package like.cn.dfs.model.namenode;

/**
 * Protobuf type {@code com.ruyuan.dfs.common.proto.UserList}
 */
public final class UserList extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.ruyuan.dfs.common.proto.UserList)
        UserListOrBuilder {
  public static final int USERENTITIES_FIELD_NUMBER = 1;
  private static final long serialVersionUID = 0L;
  // @@protoc_insertion_point(class_scope:com.ruyuan.dfs.common.proto.UserList)
  private static final like.cn.dfs.model.namenode.UserList DEFAULT_INSTANCE;
  private static final com.google.protobuf.Parser<UserList>
          PARSER = new com.google.protobuf.AbstractParser<UserList>() {
    public UserList parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserList(input, extensionRegistry);
    }
  };

  static {
    DEFAULT_INSTANCE = new like.cn.dfs.model.namenode.UserList();
  }

  private java.util.List<like.cn.dfs.model.namenode.UserEntity> userEntities_;
  private byte memoizedIsInitialized = -1;

  // Use UserList.newBuilder() to construct.
  private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private UserList() {
    userEntities_ = java.util.Collections.emptyList();
  }

  private UserList(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              userEntities_ = new java.util.ArrayList<like.cn.dfs.model.namenode.UserEntity>();
              mutable_bitField0_ |= 0x00000001;
            }
            userEntities_.add(
                    input.readMessage(like.cn.dfs.model.namenode.UserEntity.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        userEntities_ = java.util.Collections.unmodifiableList(userEntities_);
      }
      makeExtensionsImmutable();
    }
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserList parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserList parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
  }

  public static like.cn.dfs.model.namenode.UserList parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(like.cn.dfs.model.namenode.UserList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  public static like.cn.dfs.model.namenode.UserList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Parser<UserList> parser() {
    return PARSER;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
   */
  public java.util.List<like.cn.dfs.model.namenode.UserEntity> getUserEntitiesList() {
    return userEntities_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
   */
  public like.cn.dfs.model.namenode.UserEntity getUserEntities(int index) {
    return userEntities_.get(index);
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
   */
  public int getUserEntitiesCount() {
    return userEntities_.size();
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
   */
  public java.util.List<? extends like.cn.dfs.model.namenode.UserEntityOrBuilder>
  getUserEntitiesOrBuilderList() {
    return userEntities_;
  }

  /**
   * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
   */
  public like.cn.dfs.model.namenode.UserEntityOrBuilder getUserEntitiesOrBuilder(
          int index) {
    return userEntities_.get(index);
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof like.cn.dfs.model.namenode.UserList)) {
      return super.equals(obj);
    }
    like.cn.dfs.model.namenode.UserList other = ( like.cn.dfs.model.namenode.UserList ) obj;

    boolean result = true;
    result = result && getUserEntitiesList()
            .equals(other.getUserEntitiesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserEntitiesCount() > 0) {
      hash = (37 * hash) + USERENTITIES_FIELD_NUMBER;
      hash = (53 * hash) + getUserEntitiesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public Builder newBuilderForType() {return newBuilder();}

  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserList> getParserForType() {
    return PARSER;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    like.cn.dfs.model.namenode.UserList.class, like.cn.dfs.model.namenode.UserList.Builder.class);
  }

  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    for (int i = 0; i < userEntities_.size(); i++) {
      output.writeMessage(1, userEntities_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userEntities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, userEntities_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  public like.cn.dfs.model.namenode.UserList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

  /**
   * Protobuf type {@code com.ruyuan.dfs.common.proto.UserList}
   */
  public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.ruyuan.dfs.common.proto.UserList)
          like.cn.dfs.model.namenode.UserListOrBuilder {
    private int bitField0_;
    private java.util.List<like.cn.dfs.model.namenode.UserEntity> userEntities_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder> userEntitiesBuilder_;

    // Construct using like.cn.dfs.model.namenode.UserList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor;
    }

    public like.cn.dfs.model.namenode.UserList getDefaultInstanceForType() {
      return like.cn.dfs.model.namenode.UserList.getDefaultInstance();
    }

    public like.cn.dfs.model.namenode.UserList build() {
      like.cn.dfs.model.namenode.UserList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public like.cn.dfs.model.namenode.UserList buildPartial() {
      like.cn.dfs.model.namenode.UserList result = new like.cn.dfs.model.namenode.UserList(this);
      int from_bitField0_ = bitField0_;
      if (userEntitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userEntities_ = java.util.Collections.unmodifiableList(userEntities_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userEntities_ = userEntities_;
      } else {
        result.userEntities_ = userEntitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return super.clone();
    }

    public Builder clear() {
      super.clear();
      if (userEntitiesBuilder_ == null) {
        userEntities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        userEntitiesBuilder_.clear();
      }
      return this;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      like.cn.dfs.model.namenode.UserList.class, like.cn.dfs.model.namenode.UserList.Builder.class);
    }

    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return like.cn.dfs.model.namenode.Namenode.internal_static_com_ruyuan_dfs_common_proto_UserList_descriptor;
    }

    public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.setField(field, value);
    }

    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
      return super.addRepeatedField(field, value);
    }

    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof like.cn.dfs.model.namenode.UserList) {
        return mergeFrom(( like.cn.dfs.model.namenode.UserList ) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      like.cn.dfs.model.namenode.UserList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = ( like.cn.dfs.model.namenode.UserList ) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    public Builder mergeFrom(like.cn.dfs.model.namenode.UserList other) {
      if (other == like.cn.dfs.model.namenode.UserList.getDefaultInstance()) return this;
      if (userEntitiesBuilder_ == null) {
        if (!other.userEntities_.isEmpty()) {
          if (userEntities_.isEmpty()) {
            userEntities_ = other.userEntities_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserEntitiesIsMutable();
            userEntities_.addAll(other.userEntities_);
          }
          onChanged();
        }
      } else {
        if (!other.userEntities_.isEmpty()) {
          if (userEntitiesBuilder_.isEmpty()) {
            userEntitiesBuilder_.dispose();
            userEntitiesBuilder_ = null;
            userEntities_ = other.userEntities_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userEntitiesBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getUserEntitiesFieldBuilder() : null;
          } else {
            userEntitiesBuilder_.addAllMessages(other.userEntities_);
          }
        }
      }
      onChanged();
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.UserEntity> getUserEntitiesList() {
      if (userEntitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userEntities_);
      } else {
        return userEntitiesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity getUserEntities(int index) {
      if (userEntitiesBuilder_ == null) {
        return userEntities_.get(index);
      } else {
        return userEntitiesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public int getUserEntitiesCount() {
      if (userEntitiesBuilder_ == null) {
        return userEntities_.size();
      } else {
        return userEntitiesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public java.util.List<? extends like.cn.dfs.model.namenode.UserEntityOrBuilder>
    getUserEntitiesOrBuilderList() {
      if (userEntitiesBuilder_ != null) {
        return userEntitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userEntities_);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public like.cn.dfs.model.namenode.UserEntityOrBuilder getUserEntitiesOrBuilder(
            int index) {
      if (userEntitiesBuilder_ == null) {
        return userEntities_.get(index);
      } else {
        return userEntitiesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder setUserEntities(
            int index, like.cn.dfs.model.namenode.UserEntity value) {
      if (userEntitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserEntitiesIsMutable();
        userEntities_.set(index, value);
        onChanged();
      } else {
        userEntitiesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder setUserEntities(
            int index, like.cn.dfs.model.namenode.UserEntity.Builder builderForValue) {
      if (userEntitiesBuilder_ == null) {
        ensureUserEntitiesIsMutable();
        userEntities_.set(index, builderForValue.build());
        onChanged();
      } else {
        userEntitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder addUserEntities(like.cn.dfs.model.namenode.UserEntity value) {
      if (userEntitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserEntitiesIsMutable();
        userEntities_.add(value);
        onChanged();
      } else {
        userEntitiesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder addUserEntities(
            int index, like.cn.dfs.model.namenode.UserEntity value) {
      if (userEntitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserEntitiesIsMutable();
        userEntities_.add(index, value);
        onChanged();
      } else {
        userEntitiesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder addUserEntities(
            like.cn.dfs.model.namenode.UserEntity.Builder builderForValue) {
      if (userEntitiesBuilder_ == null) {
        ensureUserEntitiesIsMutable();
        userEntities_.add(builderForValue.build());
        onChanged();
      } else {
        userEntitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder addUserEntities(
            int index, like.cn.dfs.model.namenode.UserEntity.Builder builderForValue) {
      if (userEntitiesBuilder_ == null) {
        ensureUserEntitiesIsMutable();
        userEntities_.add(index, builderForValue.build());
        onChanged();
      } else {
        userEntitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder addAllUserEntities(
            java.lang.Iterable<? extends like.cn.dfs.model.namenode.UserEntity> values) {
      if (userEntitiesBuilder_ == null) {
        ensureUserEntitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, userEntities_);
        onChanged();
      } else {
        userEntitiesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder clearUserEntities() {
      if (userEntitiesBuilder_ == null) {
        userEntities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userEntitiesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public Builder removeUserEntities(int index) {
      if (userEntitiesBuilder_ == null) {
        ensureUserEntitiesIsMutable();
        userEntities_.remove(index);
        onChanged();
      } else {
        userEntitiesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity.Builder getUserEntitiesBuilder(
            int index) {
      return getUserEntitiesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity.Builder addUserEntitiesBuilder() {
      return getUserEntitiesFieldBuilder().addBuilder(
              like.cn.dfs.model.namenode.UserEntity.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public like.cn.dfs.model.namenode.UserEntity.Builder addUserEntitiesBuilder(
            int index) {
      return getUserEntitiesFieldBuilder().addBuilder(
              index, like.cn.dfs.model.namenode.UserEntity.getDefaultInstance());
    }

    /**
     * <code>repeated .com.ruyuan.dfs.common.proto.UserEntity userEntities = 1;</code>
     */
    public java.util.List<like.cn.dfs.model.namenode.UserEntity.Builder>
    getUserEntitiesBuilderList() {
      return getUserEntitiesFieldBuilder().getBuilderList();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUserEntitiesFieldBuilder();
      }
    }

    private void ensureUserEntitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        userEntities_ = new java.util.ArrayList<like.cn.dfs.model.namenode.UserEntity>(userEntities_);
        bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder>
    getUserEntitiesFieldBuilder() {
      if (userEntitiesBuilder_ == null) {
        userEntitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                like.cn.dfs.model.namenode.UserEntity, like.cn.dfs.model.namenode.UserEntity.Builder, like.cn.dfs.model.namenode.UserEntityOrBuilder>(
                userEntities_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        userEntities_ = null;
      }
      return userEntitiesBuilder_;
    }


    // @@protoc_insertion_point(builder_scope:com.ruyuan.dfs.common.proto.UserList)
  }

}
