// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backupnode.proto

package like.cn.dfs.model.backup;

public interface FetchEditsLogRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.FetchEditsLogRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 txId = 1;</code>
     */
    long getTxId();

    /**
     * <code>bool needSlots = 2;</code>
     */
    boolean getNeedSlots();
}
