// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

package like.cn.dfs.model.datanode;

public interface HeartbeatRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.ruyuan.dfs.common.proto.HeartbeatRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string hostname = 1;</code>
     */
    java.lang.String getHostname();

    /**
     * <code>string hostname = 1;</code>
     */
    com.google.protobuf.ByteString
    getHostnameBytes();
}
